---
sudo: required
dist: focal
notifications:
  slack:
    on_failure: always
matrix:
  fast_finish: true
  include:

    - name: "deploy bash provisioning  fedora (vagrantcloud) osquery Python 3.7  on bionic amd64"
      dist: bionic
      arch: amd64
      language: python
      python: 3.7
      before_install:
        - pip3 install virtualenv
        - virtualenv -p $(which python3) ~venvpy3
        - source ~venvpy3/bin/activate
        - pip install -r requirements.txt
      script:
        - sudo make deploy-vagrant
        - sudo make deploy-libvirt
        - sudo make deploy-fedora
      after_success:
        - sudo vagrant destroy -f # required to run Vagrantfile template        
        - sudo rm Vagrantfile # required to run Vagrantfile template     
        - deactivate 

     