---
- name: "OS fingerprinting "
  debug:
    msg:
    - " ansible_os_family: {{ hostvars[inventory_hostname].ansible_os_family }} "
    - " ansible_distribution: {{ hostvars[inventory_hostname].ansible_distribution }}"
    - " ansible_distribution_major_version: {{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
    - " ansible_distribution_release: {{ hostvars[inventory_hostname].ansible_distribution_release }}"
    - " ansible_distribution_version: {{ hostvars[inventory_hostname].ansible_distribution_version }}"


- name: Merge osquery_defaults and osquery variables
  set_fact:
    osquery_combined: "{{ osquery_defaults | combine(osquery, recursive=True) }}"

- name: "Add Debian osquery"
  include_tasks: osquery_debian.yml
  when: " ansible_os_family == 'Debian' and ansible_distribution in ['Debian','Ubuntu'] "

- name: "Add RedHat osquery"
  include_tasks: osquery_redhat.yml
  when: " ansible_os_family == 'RedHat' and ansible_distribution in ['CentOS','Scientific'] "

- name: "Add Fedora osquery"
  include_tasks: osquery_fedora.yml
  when: " ansible_os_family == 'RedHat' and ansible_distribution in ['Fedora'] "
