---
# [WARNING]: Could not find aptitude. Using apt-get instead fix
# Add specified repository into sources list.
- name: "Add an apt key by id from a keyserver"
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B
- name: "Add osquery  repository"
  apt_repository:
    repo: "deb [arch=amd64] https://osquery-packages.s3.amazonaws.com/xenial xenial main"
    state: present
- name: "APT: Install aptitude package"
  apt:
   name: aptitude
   force_apt_get: yes
- name: "Install required packages on Ubuntu"
  package:
    name: "{{ item }}"
    state: present
  with_items:
      - osquery
- name: "Allowing osquery to Access the System Log"
  template:
      src: rsyslog.conf.j2
      dest: /etc/rsyslog.conf
      owner: root
      group: root
      mode: 0644
- name: "Restart the syslog daemon"
  systemd:
    state: restarted
    name: rsyslog
- name: "Creating an osquery Configuration File"
  template:
      src: osquery.conf.j2
      dest: /etc/osquery/osquery.conf
      owner: root
      group: root
      mode: 0644
# - name: "Allowing osquery to Access the System Log"
#   command: osqueryctl config-check
# - name: "Insert a line at the end of a file."
#   lineinfile:
#    path: /Users/mdtutorials2/Documents/Ansible/line.txt
#    line: ''
# - name: "Install virtualenv using Python 2.7"
#   pip:
#     virtualenv: "/home/vagrant/zeek_27/venv"
#     requirements: /vagrant/provisioning/req27.txt
#     virtualenv_python: python2.7
#   when: " ansible_os_family == 'Debian' and ansible_distribution in ['Ubuntu'] "

# - name: "Install virtualenv using Python 3.5"
#   pip:
#     virtualenv: "/home/vagrant/ansible_35/venv"
#     requirements: /vagrant/provisioning/req35.txt
#     virtualenv_python: python3.5
#   when: " ansible_os_family == 'Debian' and ansible_distribution in ['Ubuntu'] and ansible_distribution_major_version in ['16'] and ansible_distribution_version in ['16.04']"
#
# - name: "Install virtualenv using Python 3.7"
#   pip:
#     virtualenv: "/home/vagrant/ansible_37/venv"
#     requirements: /vagrant/provisioning/req37.txt
#     virtualenv_python: python3.7
#   when: "  ansible_os_family == 'Debian' and ansible_distribution in ['Ubuntu'] and ansible_distribution_major_version in ['19'] and ansible_distribution_version in ['19.04']"
