---

- name: "Add repository key"
  apt_key:
    keyserver: "keyserver.ubuntu.com"
    id: "1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B"
    state: present

- name: "Add repository"
  apt_repository:
    repo: 'deb [arch=amd64] https://pkg.osquery.io/deb deb main'
    state: present

# - name: "Update apt cache"
#   apt: update_cache=yes

- name: "Ensure specific version of packages is installed."
  apt:
    name: "osquery={{ osquery_combined.version }}"
    update_cache: yes
    state: present
  when: "osquery_combined.version != 'latest'"


- name: "Ensure latest version of packages is installed."
  apt:
    name: "osquery"
    update_cache: yes
    state: present
  when: "osquery_combined.version == 'latest'"

- name: "Copy osquery.conf file"
  template:
    src: "osquery.conf.json"
    dest: "{{ osquery_combined.config_include_dir }}/osquery.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart osquery

- name: "Copy sysctl  file"
  template:
    src: "sysctl.conf.j2"
    dest: "/etc/sysctl.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart osquery

- name: "Make sure osquery autostarts"
  service:
    name: "{{ osquery_combined.daemon }}"
    enabled: yes
  when:
    - osquery_combined.enable_service

- name: "Restart osquery"
  service:
    name: "{{ osquery_combined.daemon }}"
    state: restarted
  when:
    - osquery_combined.enable_service
