---
- name: "Add repository"
  yum_repository:
    name: 'osquery-s3-rpm'
    description: 'name=osquery RPM repository - x86_64'
    baseurl: 'https://s3.amazonaws.com/osquery-packages/rpm/$basearch/'
    gpgkey: 'https://pkg.osquery.io/rpm/GPG'
    gpgcheck: yes
    repo_gpgcheck: no
    state: present

- name: "Ensure specific version of packages is installed."
  yum:
    state: present
    name: "osquery-{{ osquery_combined.version }}"
    update_cache: yes
  when: "osquery_combined.version != 'latest'"

- name: "Ensure latest version of packages is installed."
  yum:
    name: "osquery"
    state: present
    update_cache: yes
  when: "osquery_combined.version == 'latest'"

- name: "Copy osquery.conf file"
  template:
    src: "osquery.conf.json"
    dest: "{{ osquery_combined.config_include_dir }}/osquery.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart osquery

- name: "Copy sysctl  file"
  template:
    src: "sysctl.conf.j2"
    dest: "/etc/sysctl.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart osquery

# - name: "Make sure osquery autostarts"
#   service:
#     name: "{{ osquery_combined.daemon }}"
#     enabled: yes
#   when:
#     - osquery_combined.enable_service

- name: "Restart osquery"
  service:
    name: "{{ osquery_combined.daemon }}"
    state: restarted
  when:
    - osquery_combined.enable_service
