---
- name: "Boot all hosts"
  gather_facts: true
  hosts:  all
  become: yes
  vars:
    add_host_entries: true
    add_resolv_entries: true
  pre_tasks:
  - name: "Setting hostname"
    shell: "hostnamectl set-hostname {{ inventory_hostname }}"
  roles:
    - common

- name: "Install osquery"
  gather_facts: true
  hosts:  vg-osquery-01
  become: yes
  roles:
    - osquery

- name: "Install osquery"
  gather_facts: true
  hosts:  vg-osquery-02
  become: yes
  roles:
    - osquery

- name: "Install osquery"
  gather_facts: true
  hosts:  vg-osquery-03
  become: yes
  roles:
    - osquery

- name: "Install osquery"
  gather_facts: true
  hosts:  vg-osquery-04
  become: yes
  roles:
    - osquery
