name: "ubuntu/debian osquery CI workflow"


on:
  push:
    branches: [ feature_githubactions ]
  # pull_request:
  #   branches: [ githubactions_powershell ]


jobs:

  ubuntu-latest-job:
    name: "osquery on ubuntu-latest - ubuntu-18.04"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  
    - name: "Install osquery "
      run: |
        set -o errexit
        set -o pipefail
        set -o nounset
        set -o xtrace
        echo "=============Installing Osquery debian arm64=============="
        export OSQUERY_KEY=1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys $OSQUERY_KEY
        sudo add-apt-repository 'deb [arch=amd64] https://pkg.osquery.io/deb deb main'
        sudo apt-get update -qq && sudo apt-get install osquery -qqy
        sudo osqueryctl start osqueryd
        sudo osqueryctl status osqueryd


  # ubuntu-1804-job:
  #   name: "osquery onubuntu-18.04"
  #   runs-on: ubuntu-18.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status  
  #   - name: "Install osquery "
  #     run: |
  #       set -o errexit
  #       set -o pipefail
  #       set -o nounset
  #       set -o xtrace
  #       echo "=============Installing Osquery debian arm64=============="
  #       export OSQUERY_KEY=1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B
  #       sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys $OSQUERY_KEY
  #       sudo add-apt-repository 'deb [arch=amd64] https://pkg.osquery.io/deb deb main'
  #       sudo apt-get update -qq && sudo apt-get install osquery -qqy
  #       sudo osqueryctl start osqueryd
  #       sudo osqueryctl status osqueryd

  # ubuntu-2004-job:
  #   name: "osquery on ubuntu-20.04"
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status 
  #   - name: "Install osquery "
  #     run: |
  #       set -o errexit
  #       set -o pipefail
  #       set -o nounset
  #       set -o xtrace
  #       echo "=============Installing Osquery debian arm64=============="
  #       export OSQUERY_KEY=1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B
  #       sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys $OSQUERY_KEY
  #       sudo add-apt-repository 'deb [arch=amd64] https://pkg.osquery.io/deb deb main'
  #       sudo apt-get update -qq && sudo apt-get install osquery -qqy
  #       sudo osqueryctl start osqueryd
  #       sudo osqueryctl status osqueryd


  # ubuntu-1604-job:
  #   name: "osquery on ubuntu-16.04"
  #   runs-on: ubuntu-16.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status  
  #   - name: "Install osquery "
  #     run: |
  #       set -o errexit
  #       set -o pipefail
  #       set -o nounset
  #       set -o xtrace
  #       echo "=============Installing Osquery debian arm64=============="
  #       export OSQUERY_KEY=1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B
  #       sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys $OSQUERY_KEY
  #       sudo add-apt-repository 'deb [arch=amd64] https://pkg.osquery.io/deb deb main'
  #       sudo apt-get update -qq && sudo apt-get install osquery -qqy
  #       sudo osqueryctl start osqueryd
  #       sudo osqueryctl status osqueryd