name: "linux osquery CI workflow"


on:
  push:
    branches: [ feature_githubactions ]
  # pull_request:
  #   branches: [ githubactions_powershell ]


jobs:

  ubuntu-latest-job:
    name: "ubuntu-latest - Ubuntu 18.04.5 LTS"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  
    - name: "Set vagrant specific version"
      run: |
        set -x
        export VAGRANT_VERSION="2.2.9"
        echo $VAGRANT_VERSION
        sudo apt-get -qq update         
    - name: "Build Vagrant and Libvirt with KVM or QEMU"
      run: |
        set -x
        sudo apt-get install -y cpu-checker bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev
        sudo systemctl status libvirtd
        sudo libvirtd --version
        egrep -q 'vmx|svm' /proc/cpuinfo && echo "virtualization is  supported" || echo "virtualization is not supported"
        sudo addgroup libvirtd
        sudo adduser  $(id -un) libvirtd
        sudo kvm-ok || true  
    - name: "Installing Vagrant from deb package"
      run: |
        set -x
        echo "============================================="
        echo "=============Installing Vagrant=============="
        # sudo wget -nv https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_x86_64.deb
        sudo wget -nv https://releases.hashicorp.com/vagrant/2.2.14/vagrant_2.2.14_x86_64.deb
        # sudo dpkg -i vagrant_${VAGRANT_VERSION}_x86_64.deb
        sudo dpkg -i vagrant_2.2.14_x86_64.deb
        vagrant version
        echo "============================================="

  # ubuntu-1604-job:
  #   name: "ubuntu-16.04"
  #   runs-on: ubuntu-16.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status  

  # ubuntu-1804-job:
  #   name: "ubuntu-18.04"
  #   runs-on: ubuntu-18.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status  

  # ubuntu-2004-job:
  #   name: "ubuntu-20.04"
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status 

